name: dev_hs TRIQS tests

on:
  push:
    branches: [ "dev_hs" ]
  pull_request:
    branches: [ "dev_hs" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          lsb-release \
          wget \
          software-properties-common \
          cmake \
          ninja-build \
          clang-20 \
          clang-tools-20 \
          g++ \
          gfortran \
          hdf5-tools \
          libboost-dev \
          llvm-20-dev \
          libclang-20-dev \
          libomp-20-dev \
          libc++-20-dev \
          libc++abi-20-dev \
          libfftw3-dev \
          libgmp-dev \
          libhdf5-dev \
          libopenblas-dev \
          libopenmpi-dev \
          openmpi-bin \
          openmpi-common \
          openmpi-doc \
          python3-clang-20 \
          python3-dev \
          python3-h5py \
          python3-ipython \
          python3-mako \
          python3-matplotlib \
          python3-mpi4py \
          python3-numpy \
          python3-pip \
          python3-pytest \
          python3-scipy

    - name: Set up virtual environment
      run: |
        python3 -m venv --system-site-packages $HOME/.venv/triqs
        echo "$HOME/.venv/triqs/bin" >> $GITHUB_PATH

    - name: Set CXX variable
      run: |
        echo "CXX=clang++-20" >> $GITHUB_ENV

    - name: Add clang CXXFLAGS
      run: |
        echo "CXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV

    - name: Build and install clair
      env:
        CXXFLAGS: ""
      run: |
        git clone https://github.com/flatironinstitute/clair.git --branch unstable
        cmake -S clair -B clair/build -G Ninja -DBuild_Tests=OFF -DCMAKE_INSTALL_PREFIX=$HOME/install
        cmake --build clair/build --target install --verbose

    - name: Build and install TRIQS
      run: |
        git clone https://github.com/TRIQS/triqs.git --branch unstable
        cmake -S triqs -B triqs/build -G Ninja -DBuild_Tests=OFF -DCMAKE_INSTALL_PREFIX=$HOME/install
        cmake --build triqs/build --target install --verbose

    - name: Run TRIQS-enabled test suite
      shell: bash
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        source $HOME/install/share/triqs/triqsvars.sh
        python3 -m pytest -q